/**
 * Chrome copy for the Guided Application workspace.
 *
 * Kept in one place rather than beside each component: the launcher, the
 * header, the progress list and the browser toolbar have to agree about the
 * same words ("Guided Application", "Exit Guided Mode") and a citizen who
 * switches language must not see half the workspace in one script and half in
 * another. Missing languages fall back to English, which is also what the
 * scheme catalog does.
 *
 * Values are single-quoted one-liners so `scripts/check-locales.mjs` can audit
 * them for cross-script contamination.
 */

const EN = {
  launcherTitle: 'Guided Application Workspace',
  launcherBody: 'Fill the official form with SevaSathi beside you',
  cta: 'Open Application Workspace',
  opening: 'Opening the application portal…',
  intro: "Great! I've opened the application portal for you.\n\nI'll stay beside you and guide you through the form step by step.\n\nIf you don't understand any field, just ask me.",
  title: 'Guided Application',
  subtitle: 'AI is ready to assist you',
  status: 'AI Assistance Active',
  service: 'Service',
  demo: 'Demo workspace — no real government portal is connected',
  exit: 'Exit Guided Mode',
  progress: 'Application Progress',
  progressOf: 'of',
  currentStep: 'Current step',
  stepHelp: "I'll help you understand each field before you continue.",
  tabChat: 'AI Assistant',
  tabBrowser: 'Application',
  back: 'Go back',
  forward: 'Go forward',
  reload: 'Reload the page',
  openExternal: 'Open in a new tab',
  address: 'Website address',
  portal: 'Application portal',
  blockedTitle: 'This website cannot be opened here',
  blockedBody: 'This website asks browsers not to show it inside another app, so no app on the internet can. Open it in a window beside Sahayak Seva and carry on.',
  companionOpen: 'Open in a window beside the assistant',
  companionReopen: 'Open that window again',
  companionHint: 'The assistant stays open here. Move between the two windows the same way you move between tabs.',
  actions: [
    { id: 'explain', label: 'Explain this field', prompt: 'Please explain the fields on this part of the form in simple words.' },
    { id: 'documents', label: 'What documents do I need?', prompt: 'Which documents do I need for this application?' },
    { id: 'translate', label: 'Translate to Hindi', prompt: 'Please translate what is on this screen into Hindi.' },
    { id: 'next', label: "What's next?", prompt: 'What should I fill in next?' },
  ],
};

const HI = {
  launcherTitle: 'निर्देशित आवेदन कार्यक्षेत्र',
  launcherBody: 'आधिकारिक फॉर्म भरते हुए सेवा-साथी आपके साथ',
  cta: 'आवेदन कार्यक्षेत्र खोलें',
  opening: 'आवेदन पोर्टल खोला जा रहा है…',
  intro: 'बहुत बढ़िया! मैंने आपके लिए आवेदन पोर्टल खोल दिया है।\n\nमैं आपके बगल में रहकर फॉर्म को चरण-दर-चरण समझाऊँगा।\n\nकोई भी फ़ील्ड समझ न आए, तो बस मुझसे पूछ लीजिए।',
  title: 'निर्देशित आवेदन',
  subtitle: 'एआई आपकी सहायता के लिए तैयार है',
  status: 'एआई सहायता सक्रिय',
  service: 'सेवा',
  demo: 'डेमो कार्यक्षेत्र — कोई असली सरकारी पोर्टल जुड़ा हुआ नहीं है',
  exit: 'निर्देशित मोड बंद करें',
  progress: 'आवेदन की प्रगति',
  progressOf: 'में से',
  currentStep: 'वर्तमान चरण',
  stepHelp: 'आगे बढ़ने से पहले मैं हर फ़ील्ड समझाने में मदद करूँगा।',
  tabChat: 'एआई सहायक',
  tabBrowser: 'आवेदन',
  back: 'पीछे जाएँ',
  forward: 'आगे जाएँ',
  reload: 'पेज फिर से लोड करें',
  openExternal: 'नए टैब में खोलें',
  address: 'वेबसाइट का पता',
  portal: 'आवेदन पोर्टल',
  blockedTitle: 'यह वेबसाइट यहाँ नहीं खुल सकती',
  blockedBody: 'यह वेबसाइट ब्राउज़र से कहती है कि इसे किसी दूसरे ऐप में न दिखाया जाए, इसलिए इंटरनेट का कोई भी ऐप इसे यहाँ नहीं खोल सकता। इसे सेवा-साथी के बगल में एक खिड़की में खोलकर आगे बढ़ें।',
  companionOpen: 'सहायक के बगल में खिड़की में खोलें',
  companionReopen: 'वह खिड़की फिर से खोलें',
  companionHint: 'सहायक यहाँ खुली रहेगी। दोनों खिड़कियों के बीच जाने वैसे ही करें जैसे आप टैब बदलते हैं।',
  actions: [
    { id: 'explain', label: 'यह फ़ील्ड समझाएँ', prompt: 'कृपया इस फॉर्म के फ़ील्ड सरल भाषा में समझाएँ।' },
    { id: 'documents', label: 'कौन से दस्तावेज़ चाहिए?', prompt: 'इस आवेदन के लिए कौन से दस्तावेज़ चाहिए?' },
    { id: 'translate', label: 'हिंदी में समझाएँ', prompt: 'कृपया इस स्क्रीन पर जो लिखा है उसे हिंदी में समझाएँ।' },
    { id: 'next', label: 'आगे क्या भरें?', prompt: 'आगे क्या भरना है?' },
  ],
};

const MR = {
  launcherTitle: 'मार्गदर्शित अर्जी कार्यक्षेत्र',
  launcherBody: 'अधिकृत फॉर्म भरताना तुमच्या बाजूला सेवा-साथीसह',
  cta: 'अर्जी कार्यक्षेत्र उघडा',
  opening: 'अर्जी पोर्टल उघडत आहे…',
  intro: 'छान! मी तुमच्यासाठी अर्जी पोर्टल उघडले आहे.\n\nमी तुमच्या बाजूला राहून फॉर्म पायरीपायरी समजावून देईन.\n\nकोणतेही क्षेत्र समजले नाही, तर फक्त विचारा.',
  title: 'मार्गदर्शित अर्जी',
  subtitle: 'एआय तुमच्या मदतीसाठी तयार आहे',
  status: 'एआय मदत सक्रिय',
  service: 'सेवा',
  demo: 'डेमो कार्यक्षेत्र — कोणतेही खरे सरकारी पोर्टल जोडलेले नाही',
  exit: 'मार्गदर्शित मोड बंद करा',
  progress: 'अर्जीची प्रगती',
  progressOf: 'पैकी',
  currentStep: 'सध्याचा पायरी',
  stepHelp: 'पुढे जाण्यापूर्वी मी प्रत्येक क्षेत्र समजावून देईन.',
  tabChat: 'एआय सहाय्यक',
  tabBrowser: 'अर्जी',
  back: 'मागे जा',
  forward: 'पुढे जा',
  reload: 'पेज पुन्हा लोड करा',
  openExternal: 'नवीन टॅबमध्ये उघडा',
  address: 'वेबसाइटचा पत्ता',
  portal: 'अर्जी पोर्टल',
  blockedTitle: 'हे वेबसाइट येथे उघडत नाही',
  blockedBody: 'हे वेबसाइट ब्राउझरला सांगते की दुसऱ्या अॅपमध्ये दाखवू द्यायचे नाही, म्हणून इंटरनेटवरील कोणतेही अॅप ते येथे उघडू शकत नाही. ते सेवा-साथीच्या बाजूला खिडकीत उघडून पुढे जा.',
  companionOpen: 'सहाय्यकाच्या बाजूला खिडकीत उघडा',
  companionReopen: 'ती खिडकी पुन्हा उघडा',
  companionHint: 'सहाय्यक इथे उघडी राहील. दोन्ही खिडक्यांमध्ये जाणे तसेच करा जसे तुम्ही टॅब बदलता.',
  actions: [
    { id: 'explain', label: 'हे क्षेत्र समजावून सांगा', prompt: 'कृपया या फॉर्मची क्षेत्रे सोप्या भाषेत समजावून सांगा.' },
    { id: 'documents', label: 'कोणती कागदपत्रे हवीत?', prompt: 'या अर्जासाठी कोणती कागदपत्रे हवीत?' },
    { id: 'translate', label: 'हिंदीत सांगा', prompt: 'कृपया या स्क्रीनवरील मजकूर हिंदीत समजावून सांगा.' },
    { id: 'next', label: 'पुढे काय भरायचे?', prompt: 'पुढे काय भरायचे?' },
  ],
};

const TA = {
  launcherTitle: 'வழிகாட்டப்பட்ட விண்ணப்பக் கண்டனம்',
  launcherBody: 'அதிகாரப்பூர்வ படிவத்தை நிரப்பும்போது உங்களுடன் சேவை-துணை',
  cta: 'விண்ணப்பக் கண்டனத்தைத் திற',
  opening: 'விண்ணப்பு இணையதளம் திறக்கப்படுகிறது…',
  intro: 'சிறப்பு! உங்களுக்காக விண்ணப்பு இணையதளத்தைத் திறந்துள்ளேன்.\n\nபடிவத்தைப் படிப்படியாக விளக்குவதற்கு நான் உங்கள் பக்கத்திலேயே இருக்கிறேன்.\n\nஎந்தப் புலத்தும் புரியவில்லை என்றால், வெறுமன்றே கேளுங்கள்.',
  title: 'வழிகாட்டப்பட்ட விண்ணப்பம்',
  subtitle: 'உங்களுக்கு உதவத் AI தயாராக உள்ளது',
  status: 'AI உதவி செயலில்',
  service: 'சேவை',
  demo: 'டெமோ கண்டனம் — உண்மையான அரசு இணையதளம் இணைக்கப்படவில்லை',
  exit: 'வழிகாட்டப்பட்ட பயன்முறையை மூடு',
  progress: 'விண்ணப்ப முன்னேற்றம்',
  progressOf: 'இல்',
  currentStep: 'தற்போதைய படி',
  stepHelp: 'அடுத்து செல்வதற்கு முன் ஒவ்வொரு புலத்தையும் விளக்குகிறேன்.',
  tabChat: 'AI உதவியாளர்',
  tabBrowser: 'விண்ணப்பம்',
  back: 'பின்செல்',
  forward: 'முன்னெல்',
  reload: 'பக்கத்தை மீண்டும் ஏற்று',
  openExternal: 'புதிய தாவலில் திற',
  address: 'இணையதள முகவரி',
  portal: 'விண்ணப்பு இணையதளம்',
  blockedTitle: 'இந்த இணையதளத்தை இங்கு திறக்க முடியாது',
  blockedBody: 'இந்தத் தளம் உலகின் எந்த செயலியிலும் தம்மைக் காட்ட வேண்டாம் என்று சொல்கிறது. சேவை-துணைக்கு அருகில் ஒரு சாளையில் திறந்து தொடரவும்.',
  companionOpen: 'சேவை-துணைக்கு அருகில் சாளையில் திற',
  companionReopen: 'அந்த சாளையை மீண்டும் திற',
  companionHint: 'சேவை-துணை இங்கே திறந்தே இருக்கும். இரு சாளைகளுக்கும் இடையே நகருவது டேப் மாற்றுவது போலவே.',
  actions: [
    { id: 'explain', label: 'இந்தப் புலத்தை விளக்கு', prompt: 'இந்தப் படிவத்தின் புலங்களை எளிய சொற்களில் விளக்கவும்.' },
    { id: 'documents', label: 'எந்த ஆவணங்கள் தேவை?', prompt: 'இந்த விண்ணப்புக்கு எந்த ஆவணங்கள் தேவை?' },
    { id: 'translate', label: 'ஹிந்தியில் விளக்கு', prompt: 'இந்தத் திரையில் உள்ளதை ஹிந்தியில் விளக்கவும்.' },
    { id: 'next', label: 'அடுத்து என்ன நிரப்ப வேண்டும்?', prompt: 'அடுத்து என்ன நிரப்ப வேண்டும்?' },
  ],
};

const TE = {
  launcherTitle: 'మార్గదర్శక దరఖాస్తు కార్యక్షేత్రం',
  launcherBody: 'అధికారిక ఫారం నింపుతూ సేవా-సహాయి మీ పక్కనే',
  cta: 'దరఖాస్తు కార్యక్షేత్రం తెరవండి',
  opening: 'దరఖాస్తు పోర్టల్ తెరుచ్తున్నాము…',
  intro: 'అద్భుతం! మీ కోసం దరఖాస్తు పోర్టల్‌ను తెరిచేశాను.\n\nఫారంను దశలవారీగా వివరిస్తూ నేను మీ పక్కనే ఉంటాను.\n\nఏ ఫీల్డ్ అర్థం కాలేదంటే, నన్ను అడగండి.',
  title: 'మార్గదర్శక దరఖాస్తు',
  subtitle: 'మీకు సహాయం చేయడానికి AI సిద్ధంగా ఉంది',
  status: 'AI సహాయం క్రియాశీలం',
  service: 'సేవ',
  demo: 'డెమో కార్యక్షేత్రం — నిజ ప్రభుత్వ పోర్టల్ కలపలేదు',
  exit: 'మార్గదర్శక మోడ్ మూసివేయండి',
  progress: 'దరఖాస్తు పురోగతి',
  progressOf: 'లో',
  currentStep: 'ప్రస్తుత దశ',
  stepHelp: 'తరువాదకు ముందు ప్రతి ఫీల్డ్‌ను వివరిస్తాను.',
  tabChat: 'AI సహాయకుడు',
  tabBrowser: 'దరఖాస్తు',
  back: 'వెనుకకు',
  forward: 'ముందుకు',
  reload: 'పేజీని మళ్లీ లోడ్ చేయండి',
  openExternal: 'కొత్త ట్యాబ్‌లో తెరవండి',
  address: 'వెబ్‌సైట్ చిరునామా',
  portal: 'దరఖాస్తు పోర్టల్',
  blockedTitle: 'ఈ వెబ్‌సైట్‌ను ఇక్కడ తెరవలేం',
  blockedBody: 'ఈ సైట్ తనను ఇతర యాప్‌లలో చూపించవద్దని బ్రౌజర్‌కు చెబుతోంది. అందుకే ఇంటర్నెట్‌లో ఏ యాప్ అయినా దీన్ని ఇక్కడ తెరవలేరు. సేవా-సహాయి పక్కనే ఒక విండోలో తెరిచి కొనసాగండి.',
  companionOpen: 'సేవా-సహాయి పక్కన విండోలో తెరవండి',
  companionReopen: 'ఆ విండోను మళ్లీ తెరవండి',
  companionHint: 'సేవా-సహాయి ఇక్కడే ఉంటుంది. రెండు విండోల మధ్యకు వెళ్లేది ట్యాప్ మార్చేలాగే.',
  actions: [
    { id: 'explain', label: 'ఈ ఫీల్డ్‌ను వివరించండి', prompt: 'ఈ ఫారం ఫీల్డ్‌లను సులభంగా వివరించండి.' },
    { id: 'documents', label: 'ఏ పత్రాలు కావాలి?', prompt: 'ఈ దరఖాస్తుకు ఏ పత్రాలు కావాలి?' },
    { id: 'translate', label: 'తెలుగులో వివరించండి', prompt: 'ఈ స్క్రీన్‌పై ఉన్నది తెలుగులో వివరించండి.' },
    { id: 'next', label: 'తరువాత ఏమి నింపాలి?', prompt: 'తరువాత ఏమి నింపాలి?' },
  ],
};

const BN = {
  launcherTitle: 'নির্দেশিত আবেদন কর্মক্ষেত্র',
  launcherBody: 'সরকারি ফর্ম পূরণ করার সময় আপনার পাশেই সেবা-সহায়ক',
  cta: 'আবেদন কর্মক্ষেত্র খুলুন',
  opening: 'আবেদন পোর্টাল খোলা হচ্ছে…',
  intro: 'চমৎকার! আমি আপনার জন্য আবেদন পোর্টাল খুলে দিয়েছি।\n\nআমি আপনার পাশেই থেকে ধাপে ধাপে ফর্মটি বুঝিয়ে দেব।\n\nকোনো ঘরটি বুঝতে না পারলে, নির্দ্বিধায় আমাকে জিজ্ঞাসা করুন।',
  title: 'নির্দেশিত আবেদন',
  subtitle: 'এআই আপনাকে সাহায্য করতে প্রস্তুত',
  status: 'এআই সহায়তা সক্রিয়',
  service: 'পরিষেবা',
  demo: 'ডেমো কর্মক্ষেত্র — কোনো প্রকৃত সরকারি পোর্টাল যুক্ত নয়',
  exit: 'নির্দেশিত মোড বন্ধ করুন',
  progress: 'আবেদনের অগ্রগতি',
  progressOf: 'এর',
  currentStep: 'বর্তমান ধাপ',
  stepHelp: 'এগোনোর আগে আমি প্রতিটি ঘর বুঝিয়ে দেব।',
  tabChat: 'এআই সহায়ক',
  tabBrowser: 'আবেদন',
  back: 'পিছনে যান',
  forward: 'সামনে যান',
  reload: 'পৃষ্ঠা আবার লোড করুন',
  openExternal: 'নতুন ট্যাবে খুলুন',
  address: 'ওয়েবসাইটের ঠিকানা',
  portal: 'আবেদন পোর্টাল',
  blockedTitle: 'এই ওয়েবসাইট এখানে খোলা যাচ্ছে না',
  blockedBody: 'এই সাইট ব্রাউজারকে বলেছে অন্য অ্যাপের ভেতরে নিজেকে দেখাবে না, তাই ইন্টারনেটের কোনো অ্যাপই এখানে তা খুলতে পারে না। সেবা-সহায়কের পাশে একটি জানালায় খুলে কাজ চালিয়ে নিন।',
  companionOpen: 'সহায়কের পাশে একটি জানালায় খুলুন',
  companionReopen: 'জানালাটি আবার খুলুন',
  companionHint: 'সেবা-সহায়ক এখানেই খোলা থাকবে। দুটি জানালার মধ্যে যাওয়া ট্যাব বদলানোর মতোই।',
  actions: [
    { id: 'explain', label: 'এই ঘরটি বুঝিয়ে দিন', prompt: 'অনুগ্রহ করে এই ফর্মের ঘরগুলো সহজ ভাষায় বুঝিয়ে দিন।' },
    { id: 'documents', label: 'কোন নথি লাগবে?', prompt: 'এই আবেদনের জন্য কোন নথি লাগবে?' },
    { id: 'translate', label: 'হিন্দিতে বুঝিয়ে দিন', prompt: 'এই পর্দায় যা আছে তা হিন্দিতে বুঝিয়ে দিন।' },
    { id: 'next', label: 'এরপর কী লিখব?', prompt: 'এরপর কী লিখতে হবে?' },
  ],
};

const COPY = { en: EN, hi: HI, mr: MR, ta: TA, te: TE, bn: BN };

/** Falls back to English, which is always authored. */
export function getGuidedCopy(languageCode = 'en') {
  return COPY[languageCode] || EN;
}

export default COPY;
